version: "3.8"

services:
  web:
    build: .
    container_name: django_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "faq_project.wsgi:application"]

  redis:
    image: "redis:6.2"
    container_name: redis_cache
    restart: always
